### ISSUE TITLE
Update package to support quasar@1.5.0

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/app-extension-qoverlay#17]
dev/build-time error:

 warning  in ./node_modules/@quasar/quasar-app-extension-qoverlay/src/component/QOverlay.js

"export 'default' (imported as 'slot') was not found in 'quasar/src/utils/slot.js'

**Comment by hawkeye64** [comment]
Sorry, but yes. Quasar 1.50 broke this as well as many others. Will be fixed in 1.0.0-beta.4

**Comment by GordonBlahut** [comment]
Cool, I will check it out once it hits NPM.

I noticed you also removed the style import yet the cursor styles still work in the demo???

**Comment by hawkeye64** [comment]
@GordonBlahut
`I noticed you also removed the style import yet the cursor styles still work in the demo???`
I am not sure what you mean?

**Comment by GordonBlahut** [comment]
I was just wondering how the style rules from **overlay.styl** still end up in the demo since the `import './overlay.styl'` was removed from **QOverlay.js** but I see it happens through **index.js** pushing it to the config.

BTW the beta4 release doesn't seem to be listed on NPM yet. Not sure if something's going on or if that's intentional.
