### ISSUE TITLE
v1.0.0 outputs "rendering..." to console.log

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/app-extension-qoverlay#20]
**Describe the bug**
v1.0.0 outputs "rendering..." to console.log. The statement is included in dist/index.common.js, dist/index.esm.js, and dist/index.umd.js. 

Oddly, I don't see it in the source anywayere.

**To Reproduce**
1. Go to your own codepen https://codepen.io/Hawkeye64/pen/wvBKVNB?editors=1111
2. Click on  Codepen's Console button to open the console
3. Activate any qoverlay
4. See "rendering..." in console

**Expected behavior**
No console message.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
Also, the console message is output multiple times when the overlay is displayed, not sure if it's re-rendering unnecessarily or if that's just how it works.

**Comment by hawkeye64** [comment]
I think I saw a fix to Quasar when a console.log was left in after a PR merge. That didn't come from QOverlay.
