### ISSUE TITLE
no-scroll doesn't reset scroll if component is destroyed

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/app-extension-qoverlay#21]
**Describe the bug**
When using `no-scroll` prop and the `QOverlay` is destroyed while the overlay is displayed (for example, if the overlay content allows navigation to another route), scrolling continues to be prevented even though the overlay is no longer visible, since `__preventScroll(false)` was never called.

`q-body--prevent-scroll` remains in the body class list.

**To Reproduce**
1. Open https://codepen.io/gordonblahut/pen/dyPGjzM?editors=1111
2. Check off "No scroll" and click "Full Screen"
3. Click the "Exit" button, (which has been changed to kill the q-overlay component to simulate what would happen in a route change)
4. The overlay disappears, but scrolling remains disabled.

**Expected behavior**
Once the overlay is no longer visible, previous scrolling behaviour should be restored.

**Screenshots**
N/A

**Additional context**
Maybe this would be considered a bug in `PreventScrollMixin` instead?

I also wonder if the component could/should cache whether or not scroll is already prevented prior to rendering. If there's a situation where scroll is already prevented prior to displaying the overlay and the overlay disappears, it may unexpectedly re-enable scrolling (haven't tested this, might make sense for the framework itself to handle stacking and tracking preventscroll calls if it doesn't already).

**Comment by hawkeye64** [comment]
@GordonBlahut How was it destroyed? Via a `v-if`?

**Comment by hawkeye64** [comment]
Fix will be in v1.0.1

**Comment by GordonBlahut** [comment]
In my case it gets destroyed when there's a route change while it's enabled. In the codepen sample it's via v-if.

**Comment by hawkeye64** [comment]
Let me know if the fix doesn't correct for your use-case. It should, as it's in the `beforeDestroy()` to set it back.

**Comment by GordonBlahut** [comment]
Seems to have done the trick. Thanks!
