### ISSUE TITLE
Expand cursorType validator to support more cursor options

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/app-extension-qoverlay#3]
e.g. the built-in overlay behind a `QDialog` just has a default cursor, but `QOverlay` is limited to 'pointer', 'not-allowed', or 'none', making it difficult to stay consistent. Any valid css cursor should be supported, or at least 'default'.

**Comment by hawkeye64** [comment]
Thanks for pointing this out. I'll be investigating this soon.

**Comment by hawkeye64** [comment]
Ok, so here what's at play. The cursor types being offered are coming from Quasar mouse.styl:
```css
.cursor
  &-pointer
    cursor pointer !important
  &-not-allowed
    cursor not-allowed !important
  &-inherit
    cursor inherit !important
  &-none
    cursor none !important
```

**Comment by hawkeye64** [comment]
I have adjusted the code to include all cursor types, except for `url`. This should be sufficient?
Will be available in 1.0.0-beta.3

**Comment by GordonBlahut** [comment]
Much better, thanks!

**Comment by hawkeye64** [comment]
I probably need to update the docs <sigh>
